const sampleData = {
  products: [
    {
      name: "Monstera Deliciosa",
      slug: "monstera-deliciosa",
      category: "Indoor Plants",
      description: "A popular tropical houseplant with large split leaves.",
      images: [
        "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735",
      ],
      price: "29.99",
      brand: "Green Garden",
      rating: "4.8",
      numReviews: 32,
      stock: 0,
      isFeatured: true,
      banner: "banner-monstera.jpg",
    },
    {
      name: "Snake Plant",
      slug: "snake-plant",
      category: "Indoor Plants",
      description: "Low-maintenance air-purifying plant.",
      images: [
        "https://images.unsplash.com/photo-1501004318641-b39e6451bec6",
      ],
      price: "19.99",
      brand: "Nature Plants",
      rating: "4.7",
      numReviews: 45,
      stock: 20,
      isFeatured: true,
      banner: "banner-snake.jpg",
    },
    {
      name: "Peace Lily",
      slug: "peace-lily",
      category: "Flowering Plants",
      description: "Elegant indoor plant with beautiful white blooms.",
      images: [
        "https://images.unsplash.com/photo-1512428813834-c702c7702b78",
      ],
      price: "24.99",
      brand: "Bloom House",
      rating: "4.6",
      numReviews: 28,
      stock: 18,
      isFeatured: false,
      banner: "banner-peace-lily.jpg",
    },
    {
      name: "Aloe Vera",
      slug: "aloe-vera",
      category: "Succulents",
      description: "Medicinal succulent known for its soothing gel.",
      images: [
        "https://images.unsplash.com/photo-1459156212016-c812468e2115",
      ],
      price: "14.99",
      brand: "Desert Green",
      rating: "4.9",
      numReviews: 56,
      stock: 30,
      isFeatured: true,
      banner: "banner-aloe.jpg",
    },
    {
      name: "Fiddle Leaf Fig",
      slug: "fiddle-leaf-fig",
      category: "Indoor Trees",
      description: "A stylish indoor tree with large glossy leaves.",
      images: [
        "https://images.unsplash.com/photo-1463936575829-25148e1db1b8",
      ],
      price: "49.99",
      brand: "Urban Jungle",
      rating: "4.5",
      numReviews: 21,
      stock: 0,
      isFeatured: false,
      banner: "banner-fiddle.jpg",
    },
  ],
};

export default sampleData;